language: python
sudo: required
dist: xenial

python:
  - 3.7

install:
  - pip install coverage codecov
  - python setup.py install

script:
  - coverage run -m unittest

after_success:
  - coverage report
  - codecov
