language: python

python:
  - 3.7

install:
  - pip install flake8 pylint mypy coverage codecov
  - python setup.py install

script:
  - flake8 .
  - pylint *.py
  - mypy farbfeld.py
  - coverage run -m unittest

after_success:
  - coverage report
  - codecov
